server:
  port: 8083
  
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/8cse
    username: root
    password: sunil
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true  
  